#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
make_incar_aimd.py - 根据 recipe.yaml 生成 AIMD INCAR 文件

功能：
  - 读取 recipe.yaml 的 simulation 段
  - 生成适用于凝胶电解质的 AIMD INCAR
  - 支持 Langevin 和 Nosé-Hoover 恒温器
  - 支持从 INCAR.base 继承基础参数
  - 强制设置 ISYM=0（AIMD 必须关闭对称性）

用法：
  python3 make_incar_aimd.py [--recipe recipe.yaml] [--out INCAR] [--exe vasp_std]

作者：STAR0418-ABC
"""

import argparse
import sys
import os
from datetime import datetime
from typing import Dict, Any, List, Tuple

# 尝试导入 yaml
try:
    import yaml
    HAS_YAML = True
except ImportError:
    HAS_YAML = False


def load_yaml(filepath: str) -> Dict[str, Any]:
    """加载 YAML 文件"""
    if not os.path.isfile(filepath):
        print(f"[ERROR] 配方文件不存在: {filepath}")
        sys.exit(1)

    if not HAS_YAML:
        print("[ERROR] 需要 PyYAML 库: pip install pyyaml")
        sys.exit(1)

    with open(filepath, 'r', encoding='utf-8') as f:
        data = yaml.safe_load(f)

    return data if data else {}


def parse_incar_base(filepath: str) -> Dict[str, str]:
    """
    解析 INCAR.base 文件，返回参数字典

    格式: KEY = VALUE 或 KEY=VALUE
    忽略注释行（以 # 或 ! 开头）
    """
    params = {}

    if not os.path.isfile(filepath):
        return params

    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()

            # 跳过空行和注释
            if not line or line.startswith('#') or line.startswith('!'):
                continue

            # 处理行内注释
            if '#' in line:
                line = line.split('#')[0].strip()
            if '!' in line:
                line = line.split('!')[0].strip()

            # 解析 KEY = VALUE
            if '=' in line:
                parts = line.split('=', 1)
                key = parts[0].strip().upper()
                value = parts[1].strip()
                params[key] = value

    return params


def format_ediff(value: float) -> str:
    """格式化 EDIFF 为标准科学计数法"""
    if value >= 1e-4:
        return f"{value:.1E}"
    else:
        return f"{value:.0E}"


def generate_incar_aimd(sim: Dict, base_params: Dict, exe: str = None) -> str:
    """
    生成 AIMD INCAR 内容

    参数:
        sim: simulation 配置字典
        base_params: 从 INCAR.base 继承的参数
        exe: 可执行文件名（仅用于注释）

    返回:
        INCAR 文件内容字符串
    """
    # 提取参数
    temp_c = sim.get('temperature_C', 25)
    temp_k = round(temp_c + 273.15, 1)
    dt_fs = sim.get('dt_fs', 1.0)
    nsteps = sim.get('nsteps', 10000)
    ensemble = sim.get('ensemble', 'nvt').lower()
    thermostat = sim.get('thermostat', 'langevin').lower()
    gamma = sim.get('gamma_1ps', 10.0)
    smass = sim.get('smass', -3)
    nelm = sim.get('nelm', 100)
    ediff = sim.get('ediff', 1e-5)
    encut = sim.get('encut', None)
    isym = sim.get('isym', 0)  # AIMD 必须为 0
    maxmix = sim.get('maxmix', 40)

    # 生成时间戳
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    # 需要跳过的 INCAR.base 参数（将被 AIMD 参数覆盖）
    skip_keys = [
        'IBRION', 'NSW', 'POTIM', 'TEBEG', 'TEEND', 'SMASS',
        'MDALGO', 'LANGEVIN_GAMMA', 'LWAVE', 'LCHARG',
        'NELM', 'EDIFF', 'ISTART', 'ICHARG',
        'ISYM', 'MAXMIX'  # 强制由脚本控制
    ]

    # 检查 base 中是否有 LASPH 和 ADDGRID
    has_lasph = 'LASPH' in base_params
    has_addgrid = 'ADDGRID' in base_params

    lines = []

    # ==================== 文件头注释 ====================
    lines.append("# " + "=" * 70)
    lines.append("# INCAR for AIMD - Generated by make_incar_aimd.py")
    lines.append("# " + "=" * 70)
    lines.append(f"# 生成时间: {timestamp}")
    lines.append(f"# 温度: {temp_c} °C = {temp_k} K")
    lines.append(f"# 时间步长: {dt_fs} fs")
    lines.append(f"# 总步数: {nsteps}")
    lines.append(f"# 系综: {ensemble.upper()}")
    lines.append(f"# 恒温器: {thermostat}")
    if thermostat == 'langevin':
        lines.append(f"# 摩擦系数: {gamma} 1/ps")
    lines.append(f"# ISYM: {isym} (AIMD 必须关闭对称性)")
    lines.append(f"# MAXMIX: {maxmix}")
    if exe:
        lines.append(f"# 可执行文件: {exe}")
    lines.append("# " + "=" * 70)
    lines.append("")

    # ==================== 基础参数（从 INCAR.base 继承）====================
    if base_params:
        lines.append("# ============ 继承自 INCAR.base ============")
        for key, value in base_params.items():
            if key.upper() not in skip_keys:
                lines.append(f"{key} = {value}")
        lines.append("")

    # ==================== 体系相关参数（若无 INCAR.base 则提醒）====================
    if not base_params:
        lines.append("# ============ 体系相关参数（请手动补齐）============")
        lines.append("# 注意: 未找到 INCAR.base，请确保设置以下参数:")
        lines.append("#   ENCUT  - 截断能 (eV)")
        lines.append("#   PREC   - 精度 (Normal/Accurate)")
        lines.append("#   ALGO   - 电子步算法")
        lines.append("#   ISMEAR - 展宽方法 (建议 0 用于分子/有机体系)")
        lines.append("#   SIGMA  - 展宽值 (eV)")
        lines.append("")
        if encut:
            lines.append(f"ENCUT = {encut}")
        else:
            lines.append("# ENCUT = 400  # 请根据 POTCAR 设置")
        lines.append("PREC = Normal")
        lines.append("ALGO = VeryFast  # 或 Fast，AIMD 推荐")
        lines.append("ISMEAR = 0")
        lines.append("SIGMA = 0.05")
        lines.append("")
    elif encut:
        # 如果 recipe.yaml 指定了 ENCUT，覆盖 base
        lines.append(f"ENCUT = {encut}  # 来自 recipe.yaml")
        lines.append("")

    # ==================== 初始化参数 ====================
    lines.append("# ============ 初始化 ============")
    lines.append("ISTART = 0   # 从头开始")
    lines.append("ICHARG = 2   # 使用原子电荷")
    lines.append("")

    # ==================== 电子步参数 ====================
    lines.append("# ============ 电子步收敛 ============")
    lines.append(f"NELM = {nelm}    # 最大电子步数")
    lines.append(f"EDIFF = {format_ediff(ediff)}  # 电子步收敛判据 (eV)")
    lines.append(f"MAXMIX = {maxmix}   # 电荷密度混合历史，建议 40-80")
    lines.append("")

    # ==================== AIMD 稳定性：强制 ISYM=0 ====================
    lines.append("# ============ 对称性（AIMD 必须关闭）============")
    lines.append(f"ISYM = {isym}    # AIMD 必须关闭对称性，否则可能出错")
    lines.append("")

    # ==================== MD 核心参数 ====================
    lines.append("# ============ 分子动力学 (MD) ============")
    lines.append("IBRION = 0   # MD 模式")
    lines.append(f"NSW = {nsteps}    # 离子步数")
    lines.append(f"POTIM = {dt_fs}   # 时间步长 (fs)")
    lines.append("")

    # ==================== 温度控制 ====================
    lines.append("# ============ 温度控制 ============")
    # 使用整数或一位小数表示温度
    if temp_k == int(temp_k):
        temp_k_str = str(int(temp_k))
    else:
        temp_k_str = f"{temp_k:.1f}"
    lines.append(f"TEBEG = {temp_k_str}  # 初始温度 (K) = {temp_c} °C")
    lines.append(f"TEEND = {temp_k_str}  # 终止温度 (K)")
    lines.append("")

    # ==================== 恒温器设置 ====================
    lines.append("# ============ 恒温器 ============")

    if thermostat == 'langevin':
        lines.append("MDALGO = 2   # Langevin 恒温器")
        lines.append(f"LANGEVIN_GAMMA = {gamma}  # 摩擦系数 (1/ps)")
        lines.append("# LANGEVIN_GAMMA 对每种原子类型，数值越大控温越强")
        lines.append("# 建议范围: 5-20, 凝胶体系可用 10-15")
    elif thermostat == 'nose_hoover':
        lines.append("MDALGO = 3   # Nosé-Hoover 恒温器")
        lines.append(f"SMASS = {smass}   # 质量参数")
        lines.append("# SMASS: -3=自动, 0=NVE, >0=手动设置周期")
        lines.append("# 建议: -3 (自动) 或 ~0.5-3 (手动)")
    else:
        # NVE 或未知
        lines.append("# MDALGO = 1  # NVE (微正则系综，无恒温)")
        lines.append("MDALGO = 2   # Langevin (默认)")
        lines.append(f"LANGEVIN_GAMMA = {gamma}")

    lines.append("")

    # ==================== 推荐参数：LASPH, ADDGRID ====================
    lines.append("# ============ 推荐参数 ============")
    if not has_lasph:
        lines.append("LASPH = .TRUE.   # 非球形贡献，含 d/f 电子体系推荐")
    if not has_addgrid:
        lines.append("ADDGRID = .TRUE. # 额外 FFT 网格，提高精度")
    if has_lasph or has_addgrid:
        lines.append("# LASPH/ADDGRID 已在 INCAR.base 中设置")
    lines.append("")

    # ==================== 输出控制（节省空间）====================
    lines.append("# ============ 输出控制 (AIMD 节省空间) ============")
    lines.append("LWAVE = .FALSE.   # 不写 WAVECAR")
    lines.append("LCHARG = .FALSE.  # 不写 CHGCAR")
    lines.append("LREAL = Auto      # 实空间投影 (大体系推荐)")
    lines.append("")

    # ==================== 可选优化参数 ====================
    lines.append("# ============ 性能优化 (可选) ============")
    lines.append("# NCORE = 4       # 每个 orbital 的核数 (根据节点调整)")
    lines.append("# KPAR = 1        # K点并行 (Gamma-only 设为 1)")
    lines.append("# NSIM = 4        # RMM-DIIS 并行带数")
    lines.append("")

    # ==================== 结束 ====================
    lines.append("# " + "=" * 70)
    lines.append("# 运行命令: NP=16 EXE=vasp_std run_vasp.sh")
    lines.append("# 监控: aimd_watch.sh")
    lines.append("# 后处理: python3 aimd_post.py && python3 aimd_msd.py --specie Li --dt_fs " + str(dt_fs))
    lines.append("# " + "=" * 70)

    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="根据 recipe.yaml 生成 AIMD INCAR",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例:
    # 生成 INCAR.aimd
    python3 make_incar_aimd.py

    # 直接生成 INCAR
    python3 make_incar_aimd.py --out INCAR

    # 使用自定义配方
    python3 make_incar_aimd.py --recipe my_recipe.yaml --out INCAR
        """
    )
    parser.add_argument("--recipe", default="recipe.yaml",
                        help="配方文件路径 (默认: recipe.yaml)")
    parser.add_argument("--out", default="INCAR.aimd",
                        help="输出 INCAR 文件路径 (默认: INCAR.aimd)")
    parser.add_argument("--exe", default=None,
                        help="可执行文件名 (可选，仅记录到注释)")

    args = parser.parse_args()

    print("=" * 70)
    print("make_incar_aimd.py - AIMD INCAR 生成器")
    print("=" * 70)
    print(f"配方文件: {args.recipe}")
    print(f"输出文件: {args.out}")

    # 加载配方
    data = load_yaml(args.recipe)

    # 检查 simulation 段
    sim = data.get('simulation', None)
    if sim is None:
        print("[ERROR] recipe.yaml 中未找到 'simulation' 段")
        sys.exit(1)

    mode = sim.get('mode', 'static')
    if mode != 'aimd':
        print(f"[WARN] simulation.mode = '{mode}'，非 AIMD 模式")
        print("[INFO] 将继续生成 AIMD INCAR，请确认这是您需要的")

    # 验证必需参数
    if 'temperature_C' not in sim:
        print("[ERROR] simulation 中缺少 'temperature_C'")
        sys.exit(1)

    if 'dt_fs' not in sim:
        print("[ERROR] simulation 中缺少 'dt_fs'")
        sys.exit(1)

    if 'nsteps' not in sim:
        print("[ERROR] simulation 中缺少 'nsteps'")
        sys.exit(1)

    # 读取 INCAR.base（如果存在）
    base_params = {}
    if os.path.isfile('INCAR.base'):
        print("\n>>> 检测到 INCAR.base，将继承其参数...")
        base_params = parse_incar_base('INCAR.base')
        print(f"    读取 {len(base_params)} 个参数")
    else:
        print("\n>>> 未找到 INCAR.base，将生成完整 INCAR 模板")

    # 生成 INCAR
    incar_content = generate_incar_aimd(sim, base_params, args.exe)

    # 写入文件
    with open(args.out, 'w', encoding='utf-8') as f:
        f.write(incar_content)

    print(f"\n>>> INCAR 已写入: {args.out}")

    # 打印摘要
    temp_c = sim.get('temperature_C', 25)
    temp_k = round(temp_c + 273.15, 1)
    dt_fs = sim.get('dt_fs', 1.0)
    nsteps = sim.get('nsteps', 10000)
    total_time_ps = dt_fs * nsteps / 1000.0
    maxmix = sim.get('maxmix', 40)

    print("\n" + "=" * 70)
    print("INCAR 生成摘要")
    print("=" * 70)
    print(f"温度: {temp_c} °C = {temp_k} K")
    print(f"时间步长: {dt_fs} fs")
    print(f"总步数: {nsteps}")
    print(f"总模拟时间: {total_time_ps:.2f} ps")
    print(f"恒温器: {sim.get('thermostat', 'langevin')}")
    print(f"ISYM: {sim.get('isym', 0)} (AIMD 必须为 0)")
    print(f"MAXMIX: {maxmix}")
    print("=" * 70)

    print("\n[OK] INCAR 生成完成！")
    print("\n下一步:")
    print("  1. 检查 POSCAR, POTCAR, KPOINTS 是否就绪")
    print("  2. 运行: NP=16 EXE=vasp_std run_vasp.sh")
    print("  3. 监控: aimd_watch.sh")


if __name__ == "__main__":
    main()
